name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker Image
      run: |
        docker build -t node-app .

    - name: Tag Image
      run: |
        #docker tag node-app:latest ${{ ECR_URI }}/node-app:latest
        docker tag node-app:latest 352742379644.dkr.ecr.us-east-1.amazonaws.com/node-app:latest

    - name: Push Image
      run: |
        #docker push ${{ ECR_URI }}/node:latest
        docker push 352742379644.dkr.ecr.us-east-1.amazonaws.com/node-app:latest

    - name: Update Kubeconfig
      run: |
        aws eks update-kubeconfig --name demo-cluster --region us-east-1

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
